apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-amp-amg
  region: ap-northeast-2
  version: '1.28'
iam:
  withOIDC: true
fargateProfiles:
  - name: cert-manager
    selectors:
      - namespace: cert-manager
  - name: opentelemetry-operator-system 
    selectors:
      - namespace: opentelemetry-operator-system
  - name: prometheus 
    selectors:
      - namespace: prometheus
  - name: defaultfp
    selectors:
      - namespace: default
      - namespace: kube-system
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]