apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ub-cluster
  region: ap-northeast-2
fargateProfiles:
  - name: ub-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: ub-fargate-profile